# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Chicle de Canela"
description: > # this means to ignore newlines until "email:"
   Mis escritos en un blog

email: azucena.mova@gmail.com
#blog logo
logo: "/assets/images/cc_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/bg_image_v.jpg"

name: 'Azucena MV'
author: 'Azucena MV'
author_image: "/assets/images/azucena.jpg"

paginate:	5

url: "https://azucenamv.github.io/ChicledeCanela" # the base hostname & protocol for your site
baseurl: "https://azucenamv.github.io/ChicledeCanela"
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
